### ISSUE TITLE
Disable bookmarks toolbar promo

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#473]
<img width="575" alt="Screenshot 2021-02-02 at 11 20 17" src="https://user-images.githubusercontent.com/1228153/106586408-b4c82b80-6548-11eb-8679-98d315577000.png">

**Comment by 2br-2b** [comment]
Per https://www.reddit.com/r/firefox/comments/kgpkmm/how_do_i_remove_the_text_for_quick_access_place/, adding one of these two to `userChrome.css` will hide this. I'm sure there is a better way where this can be built directly into the browser's config, but I don't have enough experience working with Firefox to know where this would belong,

``` css
/* Hide text in bookmarks bar when empty */
#personal-toolbar-empty-description {
    opacity: 0;
}

#personal-toolbar-empty-description a {
    display: none;
}
```

``` css
/* Hide text in bookmarks bar when empty */
#personal-toolbar-empty {
    display: none;
}

#PersonalToolbar {
  min-height: 24px !important;
}
```

On the other hand, both of these posts see to be downvoted, so they may not work.
