### ISSUE TITLE
Windows SDK setup in CI

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#549]
This https://github.com/ghostery/user-agent-desktop/blob/946746ededf34883ee926bf03607710527241396/fern/commands/build.js#L314-L332 should be called in CI. 
Current infra relies that vfat partition is already set up, this is a week assumption as it fails after build server restart.

**Comment by y3ti** [comment]
FYI: Currently, the partition is created and configured by mix of EC2 UserData and Jenkins Agent's init scripts:

EC2 User Data:
```
#cloud-config

disk_setup:
  /dev/nvme1n1:
    table_type: mbr
    layout:
      - [99,c]

fs_setup:
  - device: /dev/nvme1n1p1
    filesystem: vfat
    cmd: mkfs.vfat /dev/nvme1n1p1

mounts:
  - [/dev/nvme1n1p1, /mnt/vfat, vfat, "rw,uid=1000,gid=1000"]
```

Jenkins Agent's Init Script:
```
#
# Wait for cloud-init
#
echo "Waiting for cloud-init..."
sudo /usr/bin/cloud-init status --wait

#
# Download and extract Windows 10 SDK to VFAT Drive
#
echo "Prepare Windows 10 SDK..."
aws s3 cp s3://user-agent-desktop-jenkins-cache/vs2017_15.9.29.tar.bz2 - \
  | tar jx -C /mnt/vfat/ 
```
