### ISSUE TITLE
Update about support crashes table

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#69]
```css
#crashes-table tr > td > a {
  pointer-events: none;
  color: var(--in-content-page-color);
}
```
https://github.com/human-web/user-agent-desktop/pull/6/files#diff-7e31a28a124e6f2117abbc2364b55982R101-R104
